### ISSUE TITLE
Getting error using bottom-up features method 

### ISSUE THREAD

**Issue by faaizhashmi** [ruotianluo/self-critical.pytorch#129]
**while using "python script/make_bu_data.py --output_dir data/cocobu" first i face the error :**

Reading trainval/karpathy_test_resnet101_faster_rcnn_genome.tsv
Traceback (most recent call last):
File "scripts/make_bu_data.py", line 40, in
for item in reader:
File "/home/faaiz/anaconda3/lib/python3.7/csv.py", line 112, in next
row = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

**then i changed the line**
reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames = FIELDNAMES)

**To**
reader = csv.DictReader(tsv_in_file.read().decode('utf-8'), delimiter='\t', fieldnames = FIELDNAMES)

**this resolve the error but then i get this error**

Reading trainval/karpathy_test_resnet101_faster_rcnn_genome.tsv
Traceback (most recent call last):
File "scripts/make_bu_data.py", line 42, in
item['num_boxes'] = int(item['num_boxes'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**any suggestions on resolving this error. please help.**

**Comment by yuchen-ren** [comment]
I am also having the same issue:
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
**Because this csv file is not a binary file,just a text file,
then i change the line 40:**
with open(os.path.join(args.downloaded_feats, infile), "r+b") as tsv_in_file:
**to:**
with open(os.path.join(args.downloaded_feats, infile), "rt") as tsv_in_file:

**It can resolve this error.**

( **By the way,if you encounter this error later:**
Traceback (most recent call last):
  File "scripts/make_bu_data.py", line 46, in <module>
    item[field] = np.frombuffer(base64.decodestring(item[field]), 
  File "/home/t630/anaconda3/envs/pytorch1.0/lib/python3.6/base64.py", line 561, in decodestring
    return decodebytes(s)
  File "/home/t630/anaconda3/envs/pytorch1.0/lib/python3.6/base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "/home/t630/anaconda3/envs/pytorch1.0/lib/python3.6/base64.py", line 520, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
**you can change the line 44:**
item[field] = np.frombuffer(base64.decodestring(item[field]),
**to**
item[field] = np.frombuffer(base64.decodestring(bytes(item[field],'utf-8')),

**it can resolve the error**)

Good luck~
